[project]
name = "my-resume"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gunicorn>=23.0.0",
    "wagtail-resume>=2.10.0",
    "wagtail>=6.3.1",
]
