# Generated by Django 5.1.1 on 2024-10-24 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtail_resume', '0014_baseresumepage_display_last_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePage',
            fields=[
                ('baseresumepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtail_resume.baseresumepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtail_resume.baseresumepage',),
        ),
    ]
